# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='%y/%m/%d/orig'),
        ),
    ]
