# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180116_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date', '-pk')},
        ),
    ]
