# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180116_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date', '-pk')},
        ),
    ]
